syntax enable                                                           "Enable syntax highlighting

so ~/.dotfiles/vim/plugins.vim                                          "Load plugins

let mapleader = ','                                                     "Set <Leader> key

set nocompatible                                                        "Force VIM to behave 'normally'
set textwidth=0                                                         "Set hard-limit for line length
set backspace=indent,eol,start                                          "Make backspace work 'normally'
set number                                                              "Turn on line numbers
set tabstop=4 shiftwidth=4 softtabstop=4 expandtab                      "Make tabs work 'normally'
set ic                                                                  "Make searching case-insensitive
set noerrorbells visualbell t_vb=                                       "Turn off all bells
set autoread                                                            "Make vim autoload new changes to a file
set nofoldenable                                                        "Disable folds
set spell spelllang=en_us                                               "Enable spell check
set spellcapcheck=                                                      "Allow sentences to begin with lowercase letters

set exrc                                                                "Support per-project .vimrc files
set secure                                                              "^^ works safely

set wildignore=*.o,*.pyc                                                "Hide files

"Swap files out of the project root
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
set viminfo+=n~/.vim/.viminfo

"----------------Mappings----------------
"Disable arrow keys
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

"Escape key
imap jj <Esc>

"Shortcut for editing ~/.vimrc
nmap <Leader>ev :e $MYVIMRC<cr>
nmap <Leader>ed :e ~/.dotfiles<cr>

"Turn off spell check
nmap <Leader>ns :set nospell<cr>

"Set shortcuts for moving lines
nmap <C-j> :m +1<CR>
nmap <C-k> :m -2<CR>
vmap <C-j> :m '>+1<CR>gv=gv
vmap <C-k> :m '<-2<CR>gv=gv

"----------------Search-----------------
set hlsearch                                                            "Enable search highlighting
set incsearch                                                           "Highlight search incrementally

"Hide syntax highlighting after search
nmap <Leader><space> :nohlsearch<cr>

"---------------Auto-Commands------------"
augroup autosourcing
    autocmd! BufWritePost .vimrc source %
    autocmd! BufWritePost plugins.vim source %
augroup END

augroup autoreloading
    autocmd! BufWritePost * CtrlPClearCache
augroup END

"Auto-remove trailing whitespace
autocmd BufWritePre * :%s/\s\+$//e

let g:ctrlp_user_command  = '[ -d .git ] && (git ls-files && git ls-files --others) || (find %s -type f)'
