# path
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH" # brew

export PATH="$PATH:$HOME/.composer/vendor/bin"
export PATH="$PATH:$HOME/.config/yarn/global/node_modules/.bin"
export PATH="$PATH:/usr/local/opt/mysql@5.7/bin"
export PATH="$PATH:$HOME/.dotfiles/bin"
export PATH="$PATH:$HOME/.dotfiles/git/scripts"

# locale
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# preferred editor
export EDITOR="vi"

# source secrets
if [ -f ~/.dotfiles/secrets.sh ]; then
    source ~/.dotfiles/secrets.sh
fi

# source aliases
for file in ~/.dotfiles/aliases/*; do
    source "$file"
done
