# path
export PATH="/usr/local/bin:/usr/local/sbin:$HOME/.composer/vendor/bin:$HOME/.config/yarn/global/node_modules/.bin:/usr/local/opt/mysql@5.7/bin:$PATH"

# preferred editor
export EDITOR="vim"

# source aliases
for file in ~/.dotfiles/aliases/*; do
    source "$file"
done
