# path to oh-my-zsh
export ZSH=~/.oh-my-zsh

# plugins
plugins=(symfony-console autojump)

# bootstrap oh-my-zsh
source $ZSH/oh-my-zsh.sh

# custom theme
PROMPT='%{$fg[yellow]%} %{$fg[green]%}%c %{$fg[yellow]%}→ $(git_prompt_info)%{$reset_color%}'

ZSH_THEME_GIT_PROMPT_PREFIX="git:(%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$fg[yellow]%}) %{$reset_color%}"

function vi_mode_prompt_info() {
    echo "${${KEYMAP/vicmd/-- NORMAL --}/main/-- INSERT --}"
}

RPS1='$(vi_mode_prompt_info)'

# vi mode
# Updates editor information when the keymap changes.
function zle-keymap-select() {
  zle -R; zle reset-prompt
}

# Ensure that the prompt is redrawn when the terminal size changes.
TRAPWINCH() {
  zle && { zle -R; zle reset-prompt }
}

zle -N zle-keymap-select

bindkey -v

