# path to oh-my-zsh
export ZSH=~/.oh-my-zsh

# plugins
plugins=()

# bootstrap oh-my-zsh
source $ZSH/oh-my-zsh.sh

# reset
unalias l

# custom theme
PROMPT='%{$fg[yellow]%}%{$fg[green]%}%c %{$fg[yellow]%}→ $(git_prompt_info)%{$reset_color%}'

ZSH_THEME_GIT_PROMPT_PREFIX="git:(%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$fg[yellow]%}) %{$reset_color%}"

# vi mode
bindkey -v

bindkey '^P' up-line-or-beginning-search
bindkey '^N' down-line-or-beginning-search
bindkey "^?" backward-delete-char # make backspace work
bindkey '^[[Z' reverse-menu-complete # make shift-tab work
bindkey '^R' history-incremental-search-backward

# autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
