# path to oh-my-zsh
export ZSH=~/.oh-my-zsh

# highlighting
source ~/.dotfiles/zsh/highlighting.zsh

# plugins
plugins=(symfony-console zsh-syntax-highlighting alias-tips vi-mode)

# bootstrap oh-my-zsh
source $ZSH/oh-my-zsh.sh

# custom theme
PROMPT='%{$fg[yellow]%} %{$fg[green]%}%c %{$fg[yellow]%}→ $(git_prompt_info)%{$reset_color%}'

ZSH_THEME_GIT_PROMPT_PREFIX="git:(%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$fg[yellow]%}) %{$reset_color%}"

export KEYTIMEOUT=1

bindkey "^[OA" up-line-or-beginning-search
bindkey "^[OB" down-line-or-beginning-search
bindkey -M vicmd "k" up-line-or-beginning-search
bindkey -M vicmd "j" down-line-or-beginning-search

bindkey '^[[Z' reverse-menu-complete # make <shift> + <tab> work in menus
