#!/bin/sh

# git coin: COmmit aNd rebase Interactively

set -e

git commit -m "[about to be coined]"

editor="vim -c ':%s/pick \([a-z0-9]\+\) \[about to be coined\]/fixup \1 [about to be coined]/'"

GIT_SEQUENCE_EDITOR="$editor" git rebase -i $(git merge-base ${1:-master} head)
