#!/bin/sh

set -e

changes=$(git status --short)

if [[ ! -z "$changes" && $1 != "--force" ]]; then
    echo "error: index is modified. refusing to undo last commit" && exit 1
else
    git reset HEAD~1
fi
